apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: git-content
          emptyDir: {}
        - name: config-volume
          configMap:
            name: my-cm
        - name: secret-volume
          secret:
            secretName: my-secret
      containers:
        - name: git-sync
          # This container pulls git data and publishes it into volume
          # "content-from-git".  In that volume you will find a symlink
          # "current" (see -dest below) which points to a checked-out copy of
          # the master branch (see -branch) of the repo (see -repo).
          # NOTE: git-sync already runs as non-root.
          image: k8s.gcr.io/git-sync/git-sync:v3.2.2
          args:
            - -repo=https://github.com/sathiyam22/OpenShift.git
            - -branch=main
            - -depth=1
            - -wait=60
            - -dest=current
            - -root=/git
          volumeMounts:
            - name: git-content
              mountPath: /git
        - name: nginx
          image: nginx:1.10.2
          ports:
          - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: secret-volume
              mountPath: /secret
            - name: git-content
              mountPath: /git
